### ISSUE TITLE
Can’t remote play outside of local network 

### ISSUE THREAD

**Issue by ipokampo** [unknownskl/greenlight#593]
Hi, as the title says, remote play works fine in the local network, but it just shows a black screen when outside the local network.

this does not happen with the iPhone Xbox app, I can stream just fine over the internet.

Are you using any specific port or something I need to open in my NAT?

**Comment by ricflairandy** [comment]
same issues here and the same issues on ios with the official app.

**Comment by aftermathicus** [comment]
Same issue. Works on my home network no problem (Xbox and steamdeck on the same wifi).
But If each are on different wifi networks will never connect. Says “connecting to console” but never connects. 

When on different networks, connects fine with the iPhone Xbox app so it’s not the connection.

**Comment by skoshy** [comment]
It didn't work for me at first, but I just quit the app and restarted it and then it started working.

**Comment by aftermathicus** [comment]
Lucky. Tried multiple times and tried multiple different networks. No luck. Prefer remote play over xcloud, since the series x has quick resume and can play games not on xcloud. Hoping it works in future releases. (Remote play when a on different network than the Xbox I mean)

**Comment by unknownskl** [comment]
Remote streaming is not a feature of the application. It could work on some networks (mostly on ipv6) but it is really a hit and miss. The official app uses Teredo which is not implemented in this application

**Comment by neodian** [comment]
Although is not the solution I've tried the Greenlight v2 with Wireguard VPN at home and is working perfectly fine everywhere. Even tried using mobile data but there was many input lag, but on fibre works flawlessly.

**Comment by Dreamescaper** [comment]
@neodian 
Thanks a lot for a suggestion, I have set up an OpenVPN on my router, and it seems to be working fine.

**Comment by tbrownio** [comment]
I had the same issue of the Xbox not connecting on steam deck but connecting successfully on the  iPhone app. I realized that the issue was that the steam deck was automatically defaulting to my 2.4GHZ wifi network and the Xbox was on the 5GHZ. So I separated the 2.4GHZ and the 5GHZ into two WiFi networks (they used to be under the same name) and that solved the problem. Kinda annoying though for everyone else in the house.

**Comment by killam42** [comment]
With the new release beta 15, port forwarding 9002 fixed the issue I had with accessing my xbox from outside my home and it works great, thanks for the updates :)

**Comment by Trashinated1** [comment]
Enable DMZplus or something like that in your router settings.
![Annotation 2023-12-03 104305](https://github.com/unknownskl/greenlight/assets/104871230/db9a209c-93de-4d53-b445-49cbe7067690)

**Comment by IslamWahid** [comment]
just managed to do it with the new version and v2 beta15 and forwarding port 9002 (UDP) FYI

**Comment by codybrom** [comment]
> just managed to do it with the new version and v2 beta15 and forwarding port 9002 (UDP) FYI

+1 to this. Worked for me on 2.0.1

**Comment by unknownskl** [comment]
> just managed to do it with the new version and v2 beta15 and forwarding port 9002 (UDP) FYI

This is the way :) Closing the issue

**Comment by nmnmcc** [comment]
A better solution is to install and enable the Teredo client locally. If your Xbox console is behind multiple layers of NAT, forwarding port 9002 will not solve the problem. Miredo implements the Teredo client (and server) on Linux. All you need to do is install miredo through your distribution's package manager and configure Microsoft's teredo server in /etc/miredo.

**Comment by tomcreed94** [comment]
a simple thing to check is that it always has a black screen with sound, but when I activate the xbox (so that the Xbox button's light is on and so the HDMI output the Video stream starts and I can play :)

The xbox has an "on" Mode without the light on the xbox on. In this mode I always get a Black screen.


on iPhone it doesn't matter in wich mode I play. I can always see everything. 



outside of my network I try to completely activate my xbox. First Remotely over iPhone an then I activate the box so that the light goes on and the HDMI Stream to my home TV starts, and then I could start using Greenlight with sound and Video and It works flawlessly. Even better than the native app on iPhone :)
